name: trade_inn
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^0.3.8
  shared_preferences: ^0.5.11
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.0+1
  mobx: ^1.1.1
  path_provider: ^1.6.21
  flutter_mobx: ^1.1.0
  mobx_codegen: ^1.0.3
  device_info: any
  provider: ^4.0.1
  page_transition: ^1.1.6
  wifi_info_plugin: ^1.1.5
  get_mac: ^0.0.1
  http: ^0.12.2
  battery_info: ^1.0.7


dev_dependencies:
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/